config/routes.rb
Rails.application.routes.draw do
  get 'reviews/index'
  get 'reviews/show'
  get 'reviews/new'
  get 'reviews/destroy'
  devise_for :users
  root to: 'pages#home'

  resources :books do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy, :edit, :update, :index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_many_attached :photos

  has_many :reviews, dependent: :destroy
  belongs_to :user

  validates :title, presence: true
  validates :author, presence: true
  validates :genre, presence: true
  validates :published, presence: true
  validates :editor, presence: true
  validates :description, presence: true, length: { minimum: 4 }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates :title, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :books

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: :index

  def index
    @books = Book.all
    if params[:query].present?
      @books = @books.where("title ILIKE ?", "%#{params[:query]}%")
    end

    @markers = @books.geocoded.map do |book|
      {
        lat: book.latitude,
        lng: book.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {book: book}),
        image_url: helpers.asset_url("logo.png")
      }
    end
  end

  def show
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user = current_user
    if @book.save
      redirect_to book_path(@book), notice: "Your book was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @book.update(book_params)
    redirect_to book_path(@book)
  end

  def destroy
    @book.destroy
    redirect_to books_path, status: :see_other
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :genre, :published, :editor, :description, photos: [])
  end

  def set_book
    @book = Book.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @book = Book.find(params[:book_id])
    @review = Review.new
  end

  def create
    @book = Book.find(params[:book_id])
    @review = Review.new(review_params)
    @review.user = current_user
    @review.book = @book
    if @review.save
      redirect_to book_path(@book), notice: "Your review was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to books_path, notice: "Your review was successfully deleted."
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to books_path, notice: "Your review was successfully changed."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:title, :content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_form.html.erb
<%= simple_form_for(@car) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :brand %>
    <%= f.input :address,
      input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
      wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
    %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/books/_info_window.html.erb
<h2><%= book.title %></h2>
<p><%= book.address %></p>

app/views/books/edit.html.erb
<h4>Update book ?</h4>

<%= simple_form_for(@book) do |f| %>
  <%= f.input :title %>
  <%= f.input :author %>
  <%= f.input :genre %>
  <%= f.input :published %>
  <%= f.input :editor %>
  <%= f.input :description %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.submit %>
<% end %>

app/views/books/index.html.erb
<div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: books_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Type a keyword"
        %>
      <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<% if @books.any? %>
  <% @books.each do |book| %>
    <%= link_to book.title, book_path(book) %>
  <% end %>
<% else %>
  <em>Sorry, no books found.</em>
<% end %>

<p>Enregistrer un nouveau livre :</p>
<%= link_to "Ajouter", new_book_path %>


<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>

app/views/books/new.html.erb
<h4>New book ?</h4>

<%= simple_form_for(@book) do |f| %>
  <%= f.input :title %>
  <%= f.input :author %>
  <%= f.input :genre %>
  <%= f.input :published %>
  <%= f.input :editor %>
  <%= f.input :description %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.submit %>
<% end %>

app/views/books/show.html.erb
<% @book.photos.each do |photo| %>
  <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
<% end %>

<%= @book.title %>
<%= @book.author %>

<%= link_to "Delete", book_path(@book), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
<%= link_to "Retour à la liste", books_path %>

<%= link_to "Modifier le livre", edit_book_path(@book) %>

<%= link_to "Laisser un avis", new_book_review_path(@book) %>

<% @book.reviews.each do |review| %>
  <%= review.title %>
  <%= review.content %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookBnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body>
    <%= render "shared/navbar" unless ( controller_name == "pages" && action_name == "home") %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<video id="background-video" autoplay loop muted>
  <source src="https://res.cloudinary.com/dsas0wiz2/video/upload/v1671725369/development/car_video_home_page_fqfbhw.mp4" type="video/mp4">
</video>

<div class="banner-home">
  <h1>Voyagez avec nos livres</h1>
  <%= link_to "go !", books_path, class: "btn-background-purple" %>
</div>

app/views/reviews/edit.html.erb
<h4>Update review ?</h4>

<%= simple_form_for [@book, @review] do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/index.html.erb
<h3>Tous mes avis</h3>
<% current_user.reviews.each do |review| %>
  <%= review.title %>
  <%= link_to "La modifier", edit_review_path(review) %>
  <%= link_to "La supprimer", review_path(review), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
<% end %>

app/views/reviews/new.html.erb
<h4>New review ?</h4>

<%= simple_form_for [@book, @review] do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div>
    <%= link_to books_path, class: "logo-navbar" do %>
      <%= image_tag "logo.png" %>
    <% end %>
  </div>

  <div class="menu-navbar">
    <% if user_signed_in? %>
      <%= image_tag "logo.png", class: "avatar dropdown-toggle icon-user", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
        <%= link_to "Liste de mes livres", books_path, class: "dropdown-item" %>
        <%= link_to "Mes avis", reviews_path, class: "dropdown-item" %>
        <%= link_to "Déconnexion", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
      </div>
    <% else %>
      <%= link_to "Connexion", new_user_session_path, class: "nav-link" %>
    <% end %>
  </div>
</div>